{% set name = "sortedcollections" %}
{% set version = "1.1.1" %}
{% set sha256 = "3610f0afaf1f4fb9b43210b349535e9fec1ab79ac52aa8a77e420ca833d20d72" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    # uses SortedKeyList which was added in sortecontainers 2.0
    - sortedcontainers >=2.0

test:
  imports:
    - sortedcollections


about:
  home: http://www.grantjenks.com/docs/sortedcollections/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Sorted Collections'

  description: Extends the sortedcontainers library with recipes for other 
               collections.
  doc_url: http://www.grantjenks.com/docs/sortedcollections/
  dev_url: https://github.com/grantjenks/sortedcollections
  doc_source_url: https://github.com/grantjenks/sortedcollections/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - grantjenks
    - mrocklin
    - nehaljwani
