travis:
  secure:
    BINSTAR_TOKEN: dfXzFYpJPNdI5TkwDkPVWINiVIGVvJ73FreYMZta1TXkrjBF71P2dJgpu3/LurgF+LNRhoLNtg/5j/EpJjjHwHDApeaPA/chxKo9QmegEJ6rtubt7CHIsipEu0BMatIUJLzE29SSOhc7FWykznRUKWT+dRP/0ptY9M8iiF5J3jno5+F065wu2vuzb8kQVH0/XBw8pAYe3G0QiPjlgukwunI4vje1AX+SQh3oHnZwHdBhLnUoVLk33ZYdKrLmX3EEfxYBjIevx9wwovqbEyEXy6oSxBS2d6qVTeWO9KDii8HwxhmnwVHUIhp01Ibny1zifvSs5YCPOcGx6IrPkQgOmzrEcb0zAaTnxOH/fl/aovkIAOWbylMxRFa/rtBIs74U+ybxJLPbYJsUTMOAC9HVePOuh+eBGzx4h5qontDcmgxuCDb2Ie1JbAWYbXAJ/MX4G9RBfEDrpCKPuntts05m69NpA+dTwZIa80sagIJ65csVkajZW+SL1DdM9lwpjp5oajYQRywHlEQa8qcDiool4ieWjyPfjcUuKv5PdxUDrMgMsFNj9BhOiUQVZEEVPAUSpXNKh6JYge3QePKNjNhjq5btO12gyXFomVdZc9AOsF0qkw5NiYdyFQZLb9S4fQAzdDDqgcuKIxkR98B9rkA/Ez3JWBHe3ijaS9a4dWxisfk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
