travis:
  secure:
    BINSTAR_TOKEN: gJD0yaJMBiiwMkXzZnyA8v+7NSpJaK2swgV4zg4/iWXF5QsFRgAWSohJrmWP3+/5vtnzSX96qc67Q/FSKoZV3yaVNHQPD3uujer6xI/EjbVrbLDccBR9tjTq9TQHqmPBrVsmW2G42IYExm1pjhdMmYZ+P+VB/Fo489L3w6u1JkT4dTTFFiP2AotWMyc8JUR8Zt2ITdXQPMO6DDBDxmGjddTiXnagu8RXmcSwDg/qztmAUum90a9DQYaZ3BtozZxB215ClvN5VjQQT+BifJBQ2SZ9zpXjwGNxLtwfAMQC1ObDT+DwRKTBOKKSqqSNnYrrA6bxHOuWpO/L7eeBDPLMqMlDqSNbNuURFjiwcGOqHKnBH0tUmOni/sOlSIG7jPR5H6m1WAaGUI3u3kICw+zg1eR9bbymqk5BItaBSe1R0UjY418GtEYIFALQ3pP5gBsHJTRgyHUP+WzGfRySlB3gvSnH4B3Opy/Yyzrx3PfcezkVW017KPcF6RXocdswFsuX2UmZ4qkqyR06U0jdalRTeqRA/i/bQS0tJmTh9YDD/7eA2tEdRg982fd75Hkw0Uqyx9gM9D9+3zyufnSrwSAUGgsvoJ/0CG7sE+m20TEfJg7JLZCdwPO7XveHtwQ4HT3qEaRdthqGr/gqFZBl/+pqQF9ik4PogEbFn74+wuYzrfA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
